{% set version = "1.0.4" %}

package:
  name: freexl
  version: {{ version }}

source:
  url: http://www.gaia-gis.it/gaia-sins/freexl-{{ version }}.tar.gz
  sha256: 500ff1010bbceee26d4ce1b991515736bd8c0ae6894f8c38468c05c224fe7c25
  patches:
    - makefile.vc.patch  # [win]
    - nmake.opt.patch  # [win]
    - freexl.c.patch  # [win]

build:
  number: 4
  features:
    - vc{{ vc }}  # [win]
  run_exports:
    - {{ pin_subpackage('freexl') }}

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - libiconv                # [not linux]

test:
  commands:
    - test -f ${PREFIX}/lib/libfreexl.a  # [unix]
    - conda inspect linkages -p ${PREFIX} freexl  # [linux]
    - conda inspect objects -p $PREFIX freexl  # [osx]

about:
  home: https://www.gaia-gis.it/fossil/freexl/index
  license: LGPL-2.1
  license_file: COPYING
  summary: 'Extract valid data from within an Excel'

extra:
  recipe-maintainers:
    - ocefpaf
    - msarahan
