{% set version = "2.0.0rc0" %}

package:
  name: freexl
  version: {{ version }}

source:
  url: http://www.gaia-gis.it/gaia-sins/freexl-{{ version }}.tar.gz
  sha256: 80c3fe2ae1062abf56456f52518bd670f9ec3917b7f85e152b347ac6b6faf880
  patches:
    - patches/makefile.vc.patch
    - patches/nmake.opt.patch
    - patches/aarch64.patch

build:
  number: 0
  run_exports:
    - {{ pin_subpackage('freexl') }}

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - libiconv  # [win]
    - make      # [not win]

test:
  commands:
    - test -f ${PREFIX}/lib/libfreexl.a  # [unix]
    - conda inspect linkages -p ${PREFIX} $PKG_NAME  # [linux]
    - conda inspect objects -p $PREFIX $PKG_NAME  # [osx]

about:
  home: https://www.gaia-gis.it/fossil/freexl/index
  license: MPL-1.1
  license_file: COPYING
  summary: Extract valid data from within an Excel

extra:
  recipe-maintainers:
    - ocefpaf
    - msarahan