travis:
  secure:
    BINSTAR_TOKEN: M3mprR0zlPiMf6BLEhRJmWwElPUImOF/DNbpbJhfnOI0MV1kLasC6SITQG5cjlvPxjcHhEf+p0VEPTZGea2uzTl5k6sd6v/yN7S7qlQkbiN26zEPcgf0XrrKWr0Z5tg0iPRQfDslKiEChOaVvEl0bnb4+kMoyq7GS75tLZaFYTLvwK+cbR3wj4A4jbBInKJMLqZ56Q84gmBlGGHwhyqQk2eetDa6WDoe3Dz5PhkeYRDVXImT5hBvi7Y08RlVZoWZNBEGbx+zsiy1ySU90nbBNhYHCJc6oKcCR9zX/GBirhUxew1CFTvzQdoth2Cfg4v43lsYwtG3DzbIEm+hO3sePoktJ8lqf4gAk8Q7dOYzxGUgCHrwUWEkXu9EFQppGYtDkp2J+A9PLKE5AZa118jXFtLJQ5ir0fNA56uhygStMwKPl/jz1OZtmx0U++A2piJHFmcSqiUUBc2I9IFppbnkgieqAAgS8JI0x1hV6HxwofL9Uy0d8oSKk2Rn0LiMb0akler/UUp0jXtigkukt5EjLRfpyCMiuiIxCPvCD7+d12bfIDiyiCJTEsWnCcGv1ittfuDLz8JnLcJc6+e6NdmbMgF85q0f7Lyufx4YZNqkSgtnTxcTyruocBQHz7MUa5jaC6HQ6E5As0S+NaR2BWHmFDByAACzf5ualRX3OBGBqQI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
