travis:
  secure:
    BINSTAR_TOKEN: qv5XYMwzrQ3ol6yrX8E5Zg7bcgv7XCTHUQRcuTSgWnKCLu/7Ga4HpWVQf5OrjR3MdjtEqbx+WR19/7SYOzBRCLc1cM9fIZdcqQP0VG0fduNy7R/9JRkl8kho5E8h0OhLtUmd+Vy+G8tMuu/Vvbpf2NTVoSh4XIWFW1u21BgZn+OK4ZvYwUInPvqpdvc+2+TTcxFGL8bXQ8MjD4sdL5RsqD4wAFHlD5Inx6MevIF/pKc789paUotMnuhF5g+3/5Mkd7wFe3DHNXaB5m6PGWJ9SgnjtZ5zFHsfob4iLM1UVfR0u+HhPJCfI5RbG/F00lUpM4BJ7R4BH7OmA7iM7odH7rSNqsMVwyy0CSKG6Gbv3MtQ71gK4BPHcO3/lE55Q/+SXbYxdt+E78mWySAnvlmP0DW0rG6K18DuEMH2OZNDfQMKaVYmEIRYXfqvgdedRQkbGJj1hB+F8YHpaJo+y8kKFzHDOlu/9xw19Rt46SEaqHYb4K7nbTDm5Cr5geITJXX+79/6X3PLfDYJKu0rUnEzSIZO+RbVfhncuVMlvOLgpqOHTXPuo5Wroe2apVqZhOUc05jA2AhHNdQsyEs1lHWD0X0Z1XX4dHn7/ayc725iXMRTjWZ8xVpLfbqfbsb/5GrKwIkt9jFRqpVUACDCNH8IEAWGT2tHt1l2p5h6hdDXZko=
appveyor:
  secure:
    BINSTAR_TOKEN: /XxwAsgp0EItmAhoPSov/h0BtAFNj2BuuEqnhgaP9l7Rw2yLBM1lD+3q4LvpVm3B
